use_frameworks!

target 'TTSForApp_Example' do
  pod 'TTSForApp', :path => '../'

  target 'TTSForApp_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
